-- Adds 75 new medicines to the `medicines` table
-- Run this in phpMyAdmin (SQL tab) on the healthcare_system database

INSERT INTO medicines (name, description, dosage_instructions, category, price, stock_qty, is_active, created_at) VALUES
('Metformin 500mg', 'Oral diabetes medication, strip of 10', 'Take with meals, twice daily', 'Diabetes', 35.00, 200, 1, NOW()),
('Metformin 850mg', 'Higher-dose diabetes medication, strip of 10', 'Take with meals, twice daily', 'Diabetes', 45.00, 150, 1, NOW()),
('Glimepiride 2mg', 'Blood sugar control tablet, strip of 10', 'Take before breakfast', 'Diabetes', 55.00, 120, 1, NOW()),
('Insulin Glargine Injection', 'Long-acting insulin, 10ml vial', 'Inject subcutaneously once daily as directed', 'Diabetes', 450.00, 40, 1, NOW()),
('Voglibose 0.3mg', 'Post-meal blood sugar control, strip of 10', 'Take with first bite of meal', 'Diabetes', 60.00, 90, 1, NOW()),
('Amlodipine 5mg', 'Blood pressure control tablet, strip of 10', 'Take once daily, same time each day', 'Hypertension', 30.00, 180, 1, NOW()),
('Telmisartan 40mg', 'Blood pressure control tablet, strip of 10', 'Take once daily', 'Hypertension', 65.00, 140, 1, NOW()),
('Losartan 50mg', 'Blood pressure control tablet, strip of 10', 'Take once daily, with or without food', 'Hypertension', 50.00, 130, 1, NOW()),
('Atenolol 50mg', 'Beta blocker for blood pressure and heart rate', 'Take once daily, morning preferred', 'Hypertension', 40.00, 110, 1, NOW()),
('Enalapril 5mg', 'ACE inhibitor for hypertension, strip of 10', 'Take once daily', 'Hypertension', 38.00, 100, 1, NOW()),
('Atorvastatin 10mg', 'Cholesterol-lowering tablet, strip of 10', 'Take once daily at night', 'Cardiac', 70.00, 150, 1, NOW()),
('Atorvastatin 20mg', 'Higher-dose cholesterol control, strip of 10', 'Take once daily at night', 'Cardiac', 90.00, 120, 1, NOW()),
('Clopidogrel 75mg', 'Blood thinner for heart protection, strip of 10', 'Take once daily with food', 'Cardiac', 85.00, 100, 1, NOW()),
('Aspirin 75mg', 'Low-dose blood thinner, strip of 14', 'Take once daily after food', 'Cardiac', 20.00, 220, 1, NOW()),
('Nitroglycerin Sublingual Tablet', 'Chest pain relief tablet, strip of 10', 'Place under tongue during chest pain episode', 'Cardiac', 60.00, 60, 1, NOW()),
('Omeprazole 20mg', 'Acid reflux and ulcer relief, strip of 10', 'Take before breakfast on empty stomach', 'Gastric', 40.00, 200, 1, NOW()),
('Pantoprazole 40mg', 'Acidity and ulcer relief, strip of 10', 'Take before breakfast', 'Gastric', 45.00, 180, 1, NOW()),
('Ranitidine 150mg', 'Acid reducer tablet, strip of 10', 'Take before meals, twice daily', 'Gastric', 25.00, 160, 1, NOW()),
('Domperidone 10mg', 'Relieves nausea and bloating, strip of 10', 'Take 15-30 mins before meals', 'Gastric', 30.00, 150, 1, NOW()),
('ORS + Zinc Tablet', 'Diarrhea management combo, strip of 10', 'Dissolve in water, take as directed', 'Gastric', 35.00, 170, 1, NOW()),
('Antacid Suspension', 'Relieves acidity and heartburn, 200ml bottle', 'Take 1-2 tsp after meals', 'Gastric', 50.00, 130, 1, NOW()),
('Loperamide 2mg', 'Anti-diarrheal capsule, strip of 10', 'Take after each loose stool, max 4/day', 'Gastric', 28.00, 140, 1, NOW()),
('Cetirizine Syrup', 'Allergy relief for children, 60ml bottle', 'Take as directed by age/weight', 'Allergy', 40.00, 100, 1, NOW()),
('Levocetirizine 5mg', 'Non-drowsy allergy relief, strip of 10', 'Take once daily, preferably at night', 'Allergy', 35.00, 150, 1, NOW()),
('Montelukast 10mg', 'Allergy and asthma control tablet, strip of 10', 'Take once daily at night', 'Allergy', 60.00, 110, 1, NOW()),
('Fexofenadine 120mg', 'Non-drowsy antihistamine, strip of 10', 'Take once daily', 'Allergy', 55.00, 100, 1, NOW()),
('Calamine Lotion', 'Soothes itching and skin irritation, 100ml', 'Apply on affected area 2-3 times daily', 'Skin', 45.00, 120, 1, NOW()),
('Clotrimazole Cream', 'Antifungal cream for skin infections, 20g tube', 'Apply thin layer twice daily', 'Skin', 50.00, 130, 1, NOW()),
('Fusidic Acid Cream', 'Antibacterial cream for skin infections, 15g tube', 'Apply 2-3 times daily on affected area', 'Skin', 65.00, 90, 1, NOW()),
('Betamethasone Cream', 'Anti-inflammatory skin cream, 20g tube', 'Apply thin layer once or twice daily', 'Skin', 55.00, 100, 1, NOW()),
('Permethrin Lotion', 'Treats scabies and lice, 60ml bottle', 'Apply as directed, wash off after prescribed time', 'Skin', 70.00, 70, 1, NOW()),
('Salicylic Acid Ointment', 'Treats corns, calluses and warts, 20g tube', 'Apply to affected area as directed', 'Skin', 40.00, 85, 1, NOW()),
('Cough Syrup (Dry Cough)', 'Relieves dry cough and throat irritation, 100ml', 'Take 10ml 3 times daily', 'Cough & Cold', 55.00, 140, 1, NOW()),
('Cough Syrup (Wet Cough)', 'Expectorant for chest congestion, 100ml', 'Take 10ml 3 times daily after food', 'Cough & Cold', 55.00, 130, 1, NOW()),
('Levocetirizine + Montelukast', 'Combination for cold and allergy, strip of 10', 'Take once daily at night', 'Cough & Cold', 65.00, 100, 1, NOW()),
('Steam Inhaler Capsule', 'Relieves nasal and chest congestion', 'Add to hot water and inhale steam', 'Cough & Cold', 30.00, 150, 1, NOW()),
('Nasal Decongestant Spray', 'Relieves blocked nose, 15ml bottle', 'Spray 1-2 times in each nostril as needed', 'Cough & Cold', 60.00, 90, 1, NOW()),
('Throat Lozenges (Pack of 10)', 'Soothes sore throat', 'Dissolve one lozenge slowly in mouth as needed', 'Cough & Cold', 25.00, 200, 1, NOW()),
('Chloramphenicol Eye Drops', 'Treats bacterial eye infections, 10ml bottle', 'Apply 1-2 drops every 4 hours', 'Eye Care', 45.00, 90, 1, NOW()),
('Ciprofloxacin Eye Drops', 'Antibiotic eye drops for infection, 10ml', 'Apply 1-2 drops 4 times daily', 'Eye Care', 50.00, 85, 1, NOW()),
('Lubricating Eye Drops', 'Relieves dry eyes, 10ml bottle', 'Apply 1-2 drops as needed', 'Eye Care', 40.00, 100, 1, NOW()),
('Ear Drops (Antibiotic)', 'Treats ear infections, 10ml bottle', 'Apply 3-4 drops twice daily', 'Ear Care', 55.00, 70, 1, NOW()),
('Multivitamin Tablets', 'Daily multivitamin supplement, strip of 15', 'Take one tablet daily after food', 'Supplements', 90.00, 160, 1, NOW()),
('Calcium + Vitamin D3 Tablet', 'Bone health supplement, strip of 15', 'Take one tablet daily after food', 'Supplements', 85.00, 150, 1, NOW()),
('Omega-3 Fish Oil Capsules', 'Heart and brain health supplement, bottle of 30', 'Take one capsule daily with food', 'Supplements', 150.00, 100, 1, NOW()),
('Zinc Tablets', 'Immunity support supplement, strip of 15', 'Take one tablet daily after food', 'Supplements', 45.00, 130, 1, NOW()),
('Vitamin C Tablets', 'Immunity booster, strip of 15', 'Take one tablet daily', 'Supplements', 40.00, 170, 1, NOW()),
('Biotin Tablets', 'Hair and skin health supplement, strip of 15', 'Take one tablet daily', 'Supplements', 95.00, 90, 1, NOW()),
('Protein Powder (Unflavored)', 'Nutritional supplement, 200g jar', 'Mix 1 scoop with water or milk daily', 'Supplements', 350.00, 40, 1, NOW()),
('Probiotic Capsules', 'Supports gut health, strip of 10', 'Take one capsule daily on empty stomach', 'Supplements', 110.00, 80, 1, NOW()),
('Paracetamol 250mg Suspension', 'Fever relief for infants, 60ml bottle', 'Take as directed by weight/age', 'Fever', 42.00, 110, 1, NOW()),
('Ibuprofen Syrup (Children)', 'Fever and pain relief for children, 60ml', 'Take as directed by weight/age', 'Fever', 48.00, 95, 1, NOW()),
('Mefenamic Acid 500mg', 'Pain and fever relief tablet, strip of 10', 'Take with food, twice daily', 'Pain Relief', 38.00, 120, 1, NOW()),
('Tramadol 50mg', 'Moderate to severe pain relief, strip of 10', 'Take as directed, avoid alcohol', 'Pain Relief', 65.00, 60, 1, NOW()),
('Etoricoxib 90mg', 'Joint and body pain relief tablet, strip of 10', 'Take once daily after food', 'Pain Relief', 75.00, 90, 1, NOW()),
('Ketorolac Injection', 'Injectable pain relief, single vial', 'To be administered by healthcare professional', 'Pain Relief', 90.00, 40, 1, NOW()),
('Amoxicillin 500mg', 'Broad spectrum antibiotic, strip of 10', 'Take every 8 hours with food', 'Antibiotics', 65.00, 130, 1, NOW()),
('Doxycycline 100mg', 'Antibiotic for infections, strip of 10', 'Take with food, avoid dairy nearby', 'Antibiotics', 55.00, 100, 1, NOW()),
('Cefixime 200mg', 'Antibiotic for respiratory/UTI infections, strip of 10', 'Take once daily with food', 'Antibiotics', 75.00, 90, 1, NOW()),
('Metronidazole 400mg', 'Antibiotic for anaerobic infections, strip of 10', 'Take with food, avoid alcohol', 'Antibiotics', 40.00, 110, 1, NOW()),
('Clarithromycin 500mg', 'Antibiotic for respiratory infections, strip of 10', 'Take twice daily with food', 'Antibiotics', 85.00, 80, 1, NOW()),
('Norfloxacin 400mg', 'Antibiotic for UTI, strip of 10', 'Take on empty stomach, twice daily', 'Antibiotics', 60.00, 95, 1, NOW()),
('Rabeprazole 20mg', 'Acid reflux relief tablet, strip of 10', 'Take before breakfast', 'General', 45.00, 140, 1, NOW()),
('Hand Sanitizer 100ml', 'Alcohol-based hand disinfectant', 'Apply and rub hands until dry', 'General', 60.00, 250, 1, NOW()),
('Antiseptic Liquid 200ml', 'Wound cleaning antiseptic solution', 'Dilute as directed and apply to wound', 'General', 55.00, 160, 1, NOW()),
('Cotton Roll (100g)', 'Medical grade absorbent cotton', 'For wound dressing and general use', 'General', 35.00, 200, 1, NOW()),
('Adhesive Bandage Strips (Box of 20)', 'For minor cuts and wounds', 'Clean wound and apply bandage', 'General', 30.00, 220, 1, NOW()),
('Digital Thermometer', 'Measures body temperature accurately', 'Place under tongue/armpit as directed', 'General', 150.00, 60, 1, NOW()),
('Face Mask (Pack of 10)', '3-ply surgical face masks', 'Wear over nose and mouth', 'General', 50.00, 300, 1, NOW()),
('Nebulizer Solution (Salbutamol)', 'Relieves breathing difficulty, 2.5ml x 10 vials', 'Use with nebulizer machine as directed', 'Respiratory', 110.00, 70, 1, NOW()),
('Salbutamol Inhaler', 'Quick relief for asthma/breathlessness', 'Use 1-2 puffs as needed', 'Respiratory', 130.00, 85, 1, NOW()),
('Budesonide Inhaler', 'Preventive asthma control inhaler', 'Use as directed, twice daily', 'Respiratory', 180.00, 60, 1, NOW()),
('Theophylline 200mg', 'Bronchodilator for asthma/COPD, strip of 10', 'Take with food, twice daily', 'Respiratory', 45.00, 90, 1, NOW()),
('Prednisolone 5mg', 'Steroid for inflammation control, strip of 10', 'Take with food as directed by doctor', 'General', 30.00, 100, 1, NOW()),
('Diazepam 5mg', 'Anti-anxiety and muscle relaxant, strip of 10', 'Take as directed, avoid driving after use', 'General', 40.00, 50, 1, NOW()),
('Folic Acid + Iron Syrup', 'Prenatal supplement, 200ml bottle', 'Take 10ml once daily', 'Anemia', 60.00, 90, 1, NOW()),
('Vitamin B Complex Injection', 'Nerve and energy support, single vial', 'To be administered by healthcare professional', 'Supplements', 55.00, 60, 1, NOW());
